version: '3'
services:
  db:
    image: mysql:5.7.17
    ports:
      - "3308:3308"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env/development/database

  nginx:
    build: containers/nginx
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - app

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'

  app:
    build: .
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
    env_file:
      - .env/development/database
    tty: true
    stdin_open: true
    depends_on:
      - db
      - webpacker

volumes:
  db-data:
