version: '3'
services:
  db:
    image: mysql:5.7.17
    ports:
      - "3308:3308"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env/development/database

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3050 -b '0.0.0.0'"
    ports:
      - "3050:3050"
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
    env_file:
      - .env/development/database
    depends_on:
      - db

volumes:
  db-data:
